import {SessionProvider} from '../../components/SessionProvider'
import SideBar from '../../components/SideBar'
import {getServerSession} from "next-auth"
import './globals.css'
import {authOptions} from '../../pages/api/auth/[...nextauth]'
import Login from '../../components/Login'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  const session = await getServerSession(authOptions)
  console.log(session);
  
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {
            !session ? (
              <Login />
            ):
            (
            <div className='flex'>
              <SideBar />
              <div className='bg flex-1 h-full'>{children}</div>
            </div>
            )
          }

        </SessionProvider>
      </body>
    </html>
  )
}
